### ISSUE TITLE
sqlite db not created

### ISSUE THREAD

**Issue by hydrargyrum** [linuxserver/docker-lychee#58]
## Expected Behavior
It fails to create the database on install

## Current Behavior
It should create the database on install

## Steps to Reproduce
1. `docker run --rm -it -p 3000:80 -e DB_CONNECTION=sqlite lscr.io/linuxserver/lychee:latest`
2. open http://localhost:3000, go through the setup wizard steps

## Environment
**OS:** debian
**CPU architecture:** x86_64
**How docker service was installed:** distro

## Command used to create docker container (run/create/compose/screenshot)
`docker run --rm -it -p 3000:80 -e DB_CONNECTION=sqlite lscr.io/linuxserver/lychee:latest`

**Comment by j0nnymoe** [comment]
As per our docs, SQLite isn't an database option and it needs MySQL/MariaDB.

**Comment by hydrargyrum** [comment]
but why? lychee itself does support sqlite: https://lycheeorg.github.io/docs/configuration.html

**Comment by j0nnymoe** [comment]
As I haven't tested I can't confirm it works, but your docker run command does t include any persistent folder mount so it's not going to generate on the host anyways. Also looks like you have to provide the database path.

**Comment by hydrargyrum** [comment]
just added `-e DB_DATABASE=/config/my.sqlite` but it's not any better :(

I indeed did not add a volume but I'm currently just testing

**Comment by nemchik** [comment]
I'm going to provide this information for completeness, and state up front:

## This is not something we will support. This is purely for the purpose of testing.

If you create a dummy shell script:
```shell
#!/bin/sh
# no other content needed
```
and mount it into the container with `-v /path/to/dummy.sh:/etc/cont-init.d/40-config` this will replace our built in init logic with the dummy script (that does nothing). From there, you should be able to edit your `/config/.env` file to set the database variables to let you try using sqlite. Just use the variables from the page you linked, but in the `.env` file. You should not need to set them as environment variables for the docker container.

If this works, it confirms that we may be able to modify our init logic to support sqlite. I do NOT recommend using this as a permanent solution, since our init logic does multiple things (not just setting up the database environment variables), and we may change the behavior in the future, or add other init files that could break this method.

If we have confirmation that things work, we can consider how to properly support it, while also not breaking existing setups.

**Comment by drizuid** [comment]
Closing, user did not configure the container properly nor read the readme. This is not something we can or will fix.
